### ISSUE TITLE
Enable Feature Details panel

### ISSUE THREAD

**Issue by svengato** [cmdcolin/jbrowse-plugin-gwas#11]
When you click on a dot in the LinearManhattanDisplay, it would be nice to pop up the Feature Details panel listing its core details and other attributes (as in LinearBasicDisplay).

**Comment by cmdcolin** [comment]
yes, in this case, the code wouldn't really work. the current mouseover code is from the wiggle track (which is this code, which you can see, grabs the first feature that overlaps in the currently hovered x coordinate https://github.com/GMOD/jbrowse-components/blob/main/plugins/wiggle/src/WiggleRendering.tsx#L48). this is all because this plugin currently uses a lot of wiggle concepts. that is a simplifying assumption, as gwas data is similar to a wiggle track in some ways, but it needs some improvement to be able to click on individual features

**Comment by cmdcolin** [comment]
fixed in v2.0.0 :) it was added along with #2

**Comment by cmdcolin** [comment]
optimistically closing but if you are still interested in this plugin, feel free to try out

**Comment by svengato** [comment]
I will look at it next week. Thanks!

**Comment by svengato** [comment]
Vertical selection now works as desired, I can mouseover/click on either of two GWAS points at the same location but with different traits and p-values. (Great!)

Previously I was able to override the tooltip text and trait color (the latter through a jexl function), but those no longer work, so I am looking into what changed there.

**Comment by cmdcolin** [comment]
went ahead and released in new version :)

**Comment by svengato** [comment]
Both the tooltip text (through the mouseover configuration) and the trait color (through my jexl function) now work. Thanks!

**Comment by svengato** [comment]
One more thing, returning to the title of this issue: the Feature Details panel is explicitly disabled in a superclass (SharedWiggleMixin) belonging to the [jbrowse-components](https://github.com/GMOD/jbrowse-components/) repository. I have reenabled it by commenting out lines 169-174 of `jbrowse-components/plugins/wiggle/src/shared/SharedWiggleMixin.ts`, but that could have undesired side effects in other panels or plugins that inherit from SharedWiggleMixin. Is there a way to do the same thing within the GWAS plugin code?

**Comment by cmdcolin** [comment]
you might not need to comment that out anymore as I "re-enabled" click to get feature details in this repo by re-implementing it here (code: https://github.com/cmdcolin/jbrowse-plugin-gwas/blob/master/src/LinearManhattanDisplay/stateModelFactory.ts#L50-L69)

musing: it is sort of hard to undo superclass behavior to get the supersuperclass behavior...there could be a way to force it but i just copied it wholesale in that codesnippet above to fix the title of this issue

I was also thinking of just not disabling feature details on that sharedwigglmixin...people can just deal with the fact that clicking on the wiggle brings up a feature detail :)

**Comment by svengato** [comment]
I uncommented that block and Feature Details still pops up. So that is resolved, thanks.

**Comment by svengato** [comment]
Fixed in the `fix_gwas` branch - thanks.
