### ISSUE TITLE
"TypeError: e.toPrecision is not a function" after Zoom to a small region

### ISSUE THREAD

**Issue by bioShaun** [cmdcolin/jbrowse-plugin-gwas#4]
![jbrowse error](https://user-images.githubusercontent.com/22510535/147031297-03c98c9c-0bb7-46e5-b0da-1c25edd14914.png)

**Comment by cmdcolin** [comment]
Do you happen to know what jbrowse version you are using?

**Comment by cmdcolin** [comment]
ah, I found this was a real error. I don't know the full cause but a stringified score e.g. the string "0.7604" is getting passed to this function

as a precautionary measure, I can convert to number before doing toPrecision

**Comment by cmdcolin** [comment]
If you want to try out a fix, you can use this branch

`jbrowse create --branch fix_wiggle_tooltip newdirectory`

this will use this branch with a fix on it: https://github.com/GMOD/jbrowse-components/pull/2607

**Comment by cmdcolin** [comment]
This was fixed in the latest release, thanks for reporting!

**Comment by cmdcolin** [comment]
likely it would be valuable if we can get even better mouseover that gives e.g. the name of the variant you are mousing over

**Comment by cmdcolin** [comment]
see #2

**Comment by cmdcolin** [comment]
maybe can close for now though
